name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.8.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.0

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci

      - name: Run build
        run: "npm run build"

      - name: Run test
        run: "npm run test"
